import PDFDocument from 'pdfkit';
import { getBusinessSettings } from '../models/BusinessSettings.js';

type AnyDoc = Record<string, any>;
const money = (value: number) => new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN' }).format(value || 0);
const date = (value: unknown) => new Intl.DateTimeFormat('es-MX', { dateStyle: 'long' }).format(new Date(String(value)));
function header(doc: PDFKit.PDFDocument, businessName: string, title: string, folio: string) { doc.rect(0, 0, 595, 90).fill('#0f172a'); doc.font('Helvetica-Bold').fontSize(19).fillColor('#ffffff').text(businessName, 42, 28); doc.fontSize(13).text(title, 360, 28, { width: 190, align: 'right' }); doc.fontSize(10).text(folio, 360, 52, { width: 190, align: 'right' }); doc.fillColor('#0f172a'); doc.x = 42; doc.y = 120; }
export async function createQuotationPdf(item: AnyDoc) { const settings = await getBusinessSettings(); const doc = new PDFDocument({ size: 'A4', margins: { top: 42, left: 42, right: 42, bottom: 42 } }); header(doc, settings.businessName, 'COTIZACIÓN', item.folio); doc.font('Helvetica').fontSize(10).text(`Fecha: ${date(item.quotationDate)}`).text(`Cliente: ${item.clientSnapshot.name}`).text(`Teléfono: ${item.clientSnapshot.phone || 'No registrado'}`).text(`Tipo: ${item.quotationTypeName}`); if (item.references) doc.text(`Referencias: ${item.references}`); doc.moveDown().font('Helvetica-Bold').text('EQUIPOS'); item.equipment.forEach((x: any, i: number) => doc.font('Helvetica').text(`${i + 1}. ${x.equipmentType} ${x.brand || ''} ${x.model || ''}`)); doc.moveDown().font('Helvetica-Bold').text('CONCEPTOS'); doc.font('Helvetica').text(`Servicio - ${money(item.serviceAmount)}`); item.materials.forEach((x: any) => doc.text(`${x.quantity} x ${x.description} - ${money(x.quantity * x.unitPrice)}`)); doc.moveDown().font('Helvetica-Bold').fontSize(14).text(`TOTAL: ${money(item.total)}`, { align: 'right' }); if (item.notes) doc.moveDown().font('Helvetica').fontSize(9).text(`Notas: ${item.notes}`); return doc; }
export async function createWarrantyPdf(item: AnyDoc) { const settings = await getBusinessSettings(); const doc = new PDFDocument({ size: 'A4', margins: { top: 42, left: 42, right: 42, bottom: 42 } }); header(doc, settings.businessName, 'GARANTÍA', item.warrantyCode); doc.font('Helvetica').fontSize(10).text(`Orden: ${item.orderFolio}`).text(`Cliente: ${item.clientName}`).text(`Inicio: ${date(item.startDate)}`).text(`Vencimiento: ${date(item.expirationDate)}`).text(`Estado: ${item.status}`); doc.moveDown().font('Helvetica-Bold').text('PIEZAS CUBIERTAS'); doc.font('Helvetica').text(item.coveredParts.join(', ')); doc.moveDown().font('Helvetica-Bold').text('EXCLUSIONES'); doc.font('Helvetica').text(item.exclusionReason || 'Sin exclusiones registradas.'); doc.moveDown().font('Helvetica-Bold').text('TÉRMINOS'); doc.font('Helvetica').text(item.terms || 'Aplican los términos generales del taller.'); doc.moveDown().font('Helvetica-Bold').text('HISTORIAL DE RECLAMACIONES'); if (!item.claims.length) doc.font('Helvetica').text('Sin reclamaciones.'); item.claims.forEach((x: any) => doc.font('Helvetica').text(`${date(x.claimDate)} - ${x.status}: ${x.description}${x.resolution ? ` / ${x.resolution}` : ''}`)); return doc; }
