import { useCallback, useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { io } from 'socket.io-client';
import { Banknote, CircleDollarSign, ClipboardPlus, MonitorSmartphone, ReceiptText, UserPlus, Wrench, WalletCards } from 'lucide-react';
import { PageHeader, StatusBadge } from '../components/Common';
import { api, query } from '../lib/api';
import { formatDate, formatMoney } from '../lib/format';
import type { Pagination, ServiceOrder } from '../types';
import { useAuth } from '../contexts/AuthContext';

type Period = 'today' | 'week' | 'month' | 'year';
interface Summary { totals: { orders: number; equipmentReceived: number; repairsCompleted: number; clientsRegistered: number; billed: number; collected: number; outstanding: number; expenses: number; netCash: number; estimatedProfit: number }; paymentsByMethod: { _id: string; total: number; count: number }[]; ordersByStatus: { _id: string; count: number; total: number; balance: number }[] }
const labels: Record<Period, string> = { today: 'Hoy', week: 'Semana', month: 'Mes', year: 'Año' };
function range(period: Period) { const end = new Date(); const start = new Date(end); if (period === 'today') start.setHours(0, 0, 0, 0); if (period === 'week') { start.setDate(start.getDate() - ((start.getDay() + 6) % 7)); start.setHours(0, 0, 0, 0); } if (period === 'month') { start.setDate(1); start.setHours(0, 0, 0, 0); } if (period === 'year') { start.setMonth(0, 1); start.setHours(0, 0, 0, 0); } return { start, end }; }
function PaymentBadge({ order }: { order: ServiceOrder }) { if (order.total > 0 && order.balance <= 0) return <span className="status status-pagado">Pagado</span>; if (order.paidAmount > 0) return <span className="status status-pago-parcial">Parcial · saldo {formatMoney(order.balance)}</span>; return <span className="status status-sin-abono">Sin abono</span>; }

export function DashboardPage() {
  const { can } = useAuth(); const [period, setPeriod] = useState<Period>('today'); const [summary, setSummary] = useState<Summary | null>(null); const [orders, setOrders] = useState<ServiceOrder[]>([]);
  const load = useCallback(async () => { const dates = range(period); const [report, recent] = await Promise.all([can('reports:view') ? api<{ data: Summary }>(`/reports/summary?${query({ start: dates.start.toISOString(), end: dates.end.toISOString() })}`) : Promise.resolve<{ data: Summary | null }>({ data: null }), api<{ data: ServiceOrder[]; pagination: Pagination }>('/service-orders?limit=6')]); setSummary(report.data); setOrders(recent.data); }, [can, period]);
  useEffect(() => { void load().catch(() => undefined); }, [load]);
  useEffect(() => { const socket = io({ withCredentials: true }); let timer: number | undefined; const reload = () => { clearTimeout(timer); timer = window.setTimeout(() => void load(), 120); }; socket.on('orders:changed', reload); socket.on('expenses:changed', reload); return () => { clearTimeout(timer); socket.disconnect(); }; }, [load]);
  const maxStatus = Math.max(1, ...(summary?.ordersByStatus.map((item) => item.count) || [1]));
  const pie = useMemo(() => { const items = summary?.paymentsByMethod || []; const total = items.reduce((sum, item) => sum + item.total, 0); let offset = 0; const colors = ['#2563eb', '#16a34a', '#f59e0b', '#8b5cf6']; return { total, gradient: items.map((item, index) => { const start = total ? offset / total * 100 : 0; offset += item.total; const end = total ? offset / total * 100 : 0; return `${colors[index % colors.length]} ${start}% ${end}%`; }).join(', '), colors }; }, [summary]);
  return <><PageHeader title="Panel principal" description={`Resumen de ${labels[period].toLowerCase()} y actividad reciente.`} actions={can('orders:create') && <Link to="/orders/new" className="button button-primary"><ClipboardPlus size={18} />Nueva orden</Link>} />
    <div className="period-switch">{(Object.keys(labels) as Period[]).map((item) => <button key={item} className={`button ${period === item ? 'button-primary' : 'button-secondary'}`} onClick={() => setPeriod(item)}>{labels[item]}</button>)}</div>
    {summary && <><div className="stats-grid"><div className="stat-card"><span className="stat-icon blue"><ReceiptText /></span><div><span>Órdenes · {labels[period]}</span><strong>{summary.totals.orders}</strong><small>{formatMoney(summary.totals.billed)} facturado</small></div></div><div className="stat-card"><span className="stat-icon green"><Banknote /></span><div><span>Abonos · {labels[period]}</span><strong>{formatMoney(summary.totals.collected)}</strong><small>Pagos aplicados</small></div></div><div className="stat-card"><span className="stat-icon amber"><WalletCards /></span><div><span>Saldo pendiente</span><strong>{formatMoney(summary.totals.outstanding)}</strong><small>Del periodo seleccionado</small></div></div><div className="stat-card"><span className="stat-icon red"><CircleDollarSign /></span><div><span>Gastos · {labels[period]}</span><strong>{formatMoney(summary.totals.expenses)}</strong><small>Neto: {formatMoney(summary.totals.netCash)}</small></div></div><div className="stat-card"><span className="stat-icon blue"><MonitorSmartphone /></span><div><span>Equipos recibidos</span><strong>{summary.totals.equipmentReceived}</strong></div></div><div className="stat-card"><span className="stat-icon green"><Wrench /></span><div><span>Reparaciones terminadas</span><strong>{summary.totals.repairsCompleted}</strong></div></div><div className="stat-card"><span className="stat-icon amber"><UserPlus /></span><div><span>Clientes registrados</span><strong>{summary.totals.clientsRegistered}</strong></div></div></div>
      <div className="dashboard-charts"><section className="panel"><div className="panel-header"><div><h2>Órdenes por estado</h2><p>Gráfica de barras del periodo seleccionado.</p></div></div><div className="bar-chart">{summary.ordersByStatus.map((item) => <div className="bar-row" key={item._id}><span>{item._id}</span><div><i style={{ width: `${Math.max(4, item.count / maxStatus * 100)}%` }} /></div><strong>{item.count}</strong></div>)}{!summary.ordersByStatus.length && <div className="empty-inline">Sin datos en este periodo.</div>}</div></section><section className="panel"><div className="panel-header"><div><h2>Abonos por método</h2><p>Distribución del dinero recibido.</p></div></div><div className="pie-layout"><div className="pie-chart" style={{ background: pie.total ? `conic-gradient(${pie.gradient})` : 'var(--border)' }}><span>{formatMoney(pie.total)}</span></div><div className="pie-legend">{summary.paymentsByMethod.map((item, index) => <div key={item._id}><i style={{ background: pie.colors[index % pie.colors.length] }} /><span>{item._id}</span><strong>{formatMoney(item.total)}</strong></div>)}</div></div></section></div></>}
    <section className="panel"><div className="panel-header"><div><h2>Órdenes recientes</h2><p>Últimos equipos recibidos en el taller.</p></div><Link to="/orders" className="text-link">Ver todas</Link></div><div className="table-wrap"><table><thead><tr><th>Folio</th><th>Fecha</th><th>Cliente</th><th>Equipo</th><th>Total</th><th>Pago</th><th>Estado</th></tr></thead><tbody>{orders.map((order) => <tr key={order._id}><td><Link className="folio-link" to={`/orders/${order._id}`}>{order.folio}</Link></td><td>{formatDate(order.orderDate)}</td><td><strong>{order.clientSnapshot.name}</strong><small>{order.clientSnapshot.phone}</small></td><td>{order.equipment?.[0]?.equipmentType || '—'}</td><td>{formatMoney(order.total)}</td><td><PaymentBadge order={order} /></td><td><StatusBadge status={order.status} /></td></tr>)}</tbody></table>{!orders.length && <div className="empty-inline">Todavía no hay órdenes registradas.</div>}</div></section>
  </>;
}
