import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Edit3, Plus, XCircle } from 'lucide-react';
import { EmptyState, LoadingTable, PageHeader, Pagination, SearchInput } from '../components/Common';
import { Modal } from '../components/Modal';
import { useAuth } from '../contexts/AuthContext';
import { useToast } from '../contexts/ToastContext';
import { api, errorMessage, jsonBody, query } from '../lib/api';
import { formatDate, formatMoney, localDateInput } from '../lib/format';
import type { Expense, Pagination as PaginationType, ServiceOrder } from '../types';

const emptyForm = { expenseDate: localDateInput(), concept: '', category: 'Refacción', amount: 0, paymentMethod: 'Efectivo' as 'Efectivo' | 'Transferencia', serviceOrderId: '', notes: '' };
const categories = ['Refacción', 'Herramientas', 'Servicios', 'Renta', 'Nómina', 'Transporte', 'Papelería', 'Otro'];

export function ExpensesPage() {
  const { can } = useAuth(); const toast = useToast();
  const [data, setData] = useState<Expense[]>([]); const [orders, setOrders] = useState<ServiceOrder[]>([]); const [pagination, setPagination] = useState<PaginationType>({ page: 1, limit: 10, total: 0, pages: 0 });
  const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [modal, setModal] = useState(false); const [editing, setEditing] = useState<Expense | null>(null); const [form, setForm] = useState(emptyForm); const [saving, setSaving] = useState(false);
  const load = useCallback(async (page = 1) => { setLoading(true); try { const result = await api<{ data: Expense[]; pagination: PaginationType }>(`/expenses?${query({ page, limit: 10, search })}`); setData(result.data); setPagination(result.pagination); } catch (error) { toast.error(errorMessage(error)); } finally { setLoading(false); } }, [search, toast]);
  useEffect(() => { const id = window.setTimeout(() => void load(1), 250); return () => clearTimeout(id); }, [load]);
  useEffect(() => { api<{ data: ServiceOrder[] }>('/service-orders?limit=100').then((result) => setOrders(result.data)).catch(() => undefined); }, []);
  const open = (item?: Expense) => { setEditing(item || null); setForm(item ? { expenseDate: localDateInput(new Date(item.expenseDate)), concept: item.concept, category: item.category, amount: item.amount, paymentMethod: item.paymentMethod, serviceOrderId: item.serviceOrder?._id || '', notes: item.notes || '' } : { ...emptyForm, expenseDate: localDateInput() }); setModal(true); };
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { const payload = { ...form, expenseDate: new Date(`${form.expenseDate}T12:00:00`).toISOString(), ...(editing ? { revision: editing.revision } : {}) }; const result = editing ? await api<{ message: string }>(`/expenses/${editing._id}`, { method: 'PUT', ...jsonBody(payload) }) : await api<{ message: string }>('/expenses', { method: 'POST', ...jsonBody(payload) }); toast.success(result.message); setModal(false); await load(pagination.page); } catch (error) { toast.error(errorMessage(error)); } finally { setSaving(false); } };
  const cancel = async (item: Expense) => { const reason = prompt(`Motivo para cancelar ${item.expenseCode}:`); if (!reason) return; try { const result = await api<{ message: string }>(`/expenses/${item._id}/cancel`, { method: 'POST', ...jsonBody({ reason }) }); toast.success(result.message); await load(pagination.page); } catch (error) { toast.error(errorMessage(error)); } };
  return <><PageHeader title="Gastos" description="Control de compras, refacciones y salidas del taller." actions={can('expenses:create') && <button className="button button-primary" onClick={() => open()}><Plus size={18} />Nuevo gasto</button>} />
    <section className="panel"><div className="toolbar"><SearchInput value={search} onChange={setSearch} placeholder="Código, concepto o categoría…" /><span className="result-count">{pagination.total} gastos</span></div>{loading ? <LoadingTable /> : <div className="table-wrap"><table><thead><tr><th>Folio</th><th>Fecha</th><th>Concepto</th><th>Categoría</th><th>Orden</th><th>Forma de pago</th><th>Importe</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{data.map((item) => <tr key={item._id}><td><span className="code-chip">{item.expenseCode}</span></td><td>{formatDate(item.expenseDate)}</td><td><strong>{item.concept}</strong>{item.notes && <small>{item.notes}</small>}</td><td>{item.category}</td><td>{item.serviceOrder ? item.serviceOrder.folio : 'General'}</td><td>{item.paymentMethod}</td><td>{formatMoney(item.amount)}</td><td><span className={`status status-${item.status.toLowerCase()}`}>{item.status}</span></td><td><div className="row-actions">{can('expenses:edit') && item.status === 'Activo' && <button className="icon-button" onClick={() => open(item)}><Edit3 size={17} /></button>}{can('expenses:cancel') && item.status === 'Activo' && <button className="icon-button danger" onClick={() => void cancel(item)}><XCircle size={17} /></button>}</div></td></tr>)}</tbody></table>{!data.length && <EmptyState />}</div>}<Pagination page={pagination.page} pages={pagination.pages} onChange={(page) => void load(page)} /></section>
    <Modal open={modal} title={editing ? 'Editar gasto' : 'Nuevo gasto'} onClose={() => setModal(false)} size="large"><form onSubmit={submit}><div className="form-grid two"><label className="field"><span>Fecha *</span><input type="date" value={form.expenseDate} onChange={(e) => setForm({ ...form, expenseDate: e.target.value })} required /></label><label className="field"><span>Categoría *</span><input list="expense-categories" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} required /><datalist id="expense-categories">{categories.map((item) => <option key={item} value={item} />)}</datalist></label><label className="field field-span-2"><span>Concepto *</span><input value={form.concept} onChange={(e) => setForm({ ...form, concept: e.target.value })} required minLength={2} /></label><label className="field"><span>Importe *</span><input type="number" min="0.01" step="0.01" value={form.amount} onChange={(e) => setForm({ ...form, amount: Number(e.target.value) })} required /></label><label className="field"><span>Forma de pago *</span><select value={form.paymentMethod} onChange={(e) => setForm({ ...form, paymentMethod: e.target.value as 'Efectivo' | 'Transferencia' })}><option>Efectivo</option><option>Transferencia</option></select></label><label className="field field-span-2"><span>Relacionar con orden (opcional)</span><select value={form.serviceOrderId} onChange={(e) => setForm({ ...form, serviceOrderId: e.target.value })}><option value="">Gasto general</option>{orders.map((order) => <option key={order._id} value={order._id}>{order.folio} · {order.clientSnapshot.name}</option>)}</select><small>Si relacionas una refacción, el reporte evita volver a descontar su costo estimado.</small></label></div><label className="field"><span>Notas</span><textarea rows={3} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label><div className="modal-actions"><button type="button" className="button button-secondary" onClick={() => setModal(false)}>Cancelar</button><button className="button button-primary" disabled={saving}>{saving ? 'Guardando…' : 'Guardar gasto'}</button></div></form></Modal>
  </>;
}
