import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Edit3, Plus, ToggleLeft } from 'lucide-react';
import { EmptyState, LoadingTable, PageHeader, Pagination, SearchInput } from '../components/Common';
import { Modal } from '../components/Modal';
import { useAuth } from '../contexts/AuthContext';
import { useToast } from '../contexts/ToastContext';
import { api, errorMessage, jsonBody, query } from '../lib/api';
import type { OrderType, Pagination as PaginationType } from '../types';

export function OrderTypesPage() {
  const { can } = useAuth(); const toast = useToast();
  const [data, setData] = useState<OrderType[]>([]); const [pagination, setPagination] = useState<PaginationType>({ page: 1, limit: 10, total: 0, pages: 0 });
  const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [modal, setModal] = useState(false); const [editing, setEditing] = useState<OrderType | null>(null);
  const [form, setForm] = useState({ name: '', description: '', active: true }); const [saving, setSaving] = useState(false);
  const load = useCallback(async (page = 1) => { setLoading(true); try { const response = await api<{ data: OrderType[]; pagination: PaginationType }>(`/order-types?${query({ page, limit: 10, search })}`); setData(response.data); setPagination(response.pagination); } catch (error) { toast.error(errorMessage(error)); } finally { setLoading(false); } }, [search, toast]);
  useEffect(() => { const id = window.setTimeout(() => void load(1), 250); return () => window.clearTimeout(id); }, [load]);
  const open = (item?: OrderType) => { setEditing(item || null); setForm(item ? { name: item.name, description: item.description, active: item.active } : { name: '', description: '', active: true }); setModal(true); };
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { const result = editing ? await api<{ message: string }>(`/order-types/${editing._id}`, { method: 'PUT', ...jsonBody({ ...form, revision: editing.revision }) }) : await api<{ message: string }>('/order-types', { method: 'POST', ...jsonBody(form) }); toast.success(result.message); setModal(false); await load(pagination.page); } catch (error) { toast.error(errorMessage(error)); } finally { setSaving(false); } };
  const deactivate = async (item: OrderType) => { if (!confirm(`¿Desactivar ${item.name}?`)) return; try { const result = await api<{ message: string }>(`/order-types/${item._id}/deactivate`, { method: 'PATCH' }); toast.success(result.message); await load(pagination.page); } catch (error) { toast.error(errorMessage(error)); } };
  return <><PageHeader title="Tipos de orden" description="Catálogo de servicios que ofrece el taller." actions={can('orderTypes:create') && <button className="button button-primary" onClick={() => open()}><Plus size={18} />Nuevo tipo</button>} />
    <section className="panel"><div className="toolbar"><SearchInput value={search} onChange={setSearch} placeholder="Buscar tipo de servicio…" /><span className="result-count">{pagination.total} registros</span></div>{loading ? <LoadingTable /> : <div className="table-wrap"><table><thead><tr><th>Nombre</th><th>Descripción</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{data.map((item) => <tr key={item._id}><td><strong>{item.name}</strong></td><td>{item.description || '—'}</td><td><span className={`status ${item.active ? 'status-activo' : 'status-cancelado'}`}>{item.active ? 'Activo' : 'Inactivo'}</span></td><td><div className="row-actions">{can('orderTypes:edit') && <button className="icon-button" onClick={() => open(item)}><Edit3 size={17} /></button>}{can('orderTypes:deactivate') && item.active && <button className="icon-button danger" onClick={() => void deactivate(item)}><ToggleLeft size={18} /></button>}</div></td></tr>)}</tbody></table>{!data.length && <EmptyState />}</div>}<Pagination page={pagination.page} pages={pagination.pages} onChange={(page) => void load(page)} /></section>
    <Modal open={modal} title={editing ? 'Editar tipo de orden' : 'Nuevo tipo de orden'} onClose={() => setModal(false)}><form onSubmit={submit}><label className="field"><span>Nombre *</span><input autoFocus value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required minLength={2} /></label><label className="field"><span>Descripción</span><textarea rows={3} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><div className="modal-actions"><button type="button" className="button button-secondary" onClick={() => setModal(false)}>Cancelar</button><button className="button button-primary" disabled={saving}>{saving ? 'Guardando…' : 'Guardar'}</button></div></form></Modal></>;
}
