import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { io } from 'socket.io-client';
import { Download, Edit3, Eye, Plus } from 'lucide-react';
import { EmptyState, LoadingTable, PageHeader, Pagination, SearchInput, StatusBadge } from '../components/Common';
import { useAuth } from '../contexts/AuthContext';
import { useToast } from '../contexts/ToastContext';
import { api, errorMessage, openPdf, query } from '../lib/api';
import { formatDate, formatMoney } from '../lib/format';
import type { Pagination as PaginationType, ServiceOrder } from '../types';
const statuses = ['', 'Pendiente', 'En diagnostico', 'En reparacion', 'Esperando refaccion', 'Listo para entregar', 'Entregado', 'Finalizado', 'Cancelado'];
export function OrdersPage() {
  const { can } = useAuth(); const toast = useToast(); const [data, setData] = useState<ServiceOrder[]>([]); const [pagination, setPagination] = useState<PaginationType>({ page: 1, limit: 10, total: 0, pages: 0 }); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(true);
  const load = useCallback(async (page = 1) => { setLoading(true); try { const response = await api<{ data: ServiceOrder[]; pagination: PaginationType }>(`/service-orders?${query({ page, limit: 10, search, status })}`); setData(response.data); setPagination(response.pagination); } catch (error) { toast.error(errorMessage(error)); } finally { setLoading(false); } }, [search, status, toast]);
  useEffect(() => { const id = window.setTimeout(() => void load(1), 250); return () => clearTimeout(id); }, [load]); useEffect(() => { const socket = io({ withCredentials: true }); socket.on('orders:changed', () => void load(pagination.page)); return () => { socket.disconnect(); }; }, [load, pagination.page]);
  const pdf = async (order: ServiceOrder) => { try { await openPdf(`/api/service-orders/${order._id}/pdf?format=a4`); } catch (error) { toast.error(errorMessage(error)); } };
  return <><PageHeader title="Órdenes de servicio" description="Consulta, filtra y administra todos los equipos recibidos." actions={can('orders:create') && <Link className="button button-primary" to="/orders/new"><Plus size={18} />Nueva orden</Link>} /><section className="panel"><div className="toolbar toolbar-wrap"><SearchInput value={search} onChange={setSearch} placeholder="Folio, cliente, teléfono, equipo o tipo…" /><label className="select-filter"><span>Estado</span><select value={status} onChange={(e) => setStatus(e.target.value)}>{statuses.map((item) => <option key={item} value={item}>{item || 'Todos los estados'}</option>)}</select></label><span className="result-count">{pagination.total} órdenes</span></div>{loading ? <LoadingTable /> : <div className="table-wrap"><table><thead><tr><th>Folio</th><th>Fecha</th><th>Cliente</th><th>Equipo(s)</th><th>Tipo</th><th>Total</th><th>Saldo</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{data.map((order) => <tr key={order._id}><td><Link className="folio-link" to={`/orders/${order._id}`}>{order.folio}</Link></td><td>{formatDate(order.orderDate)}</td><td><strong>{order.clientSnapshot.name}</strong><small>{order.clientSnapshot.phone}</small></td><td>{order.equipment.map((item) => <span className="equipment-list-item" key={item._id || `${item.equipmentType}-${item.serialNumber}`}>{[item.equipmentType, item.brand, item.model].filter(Boolean).join(' ')}</span>)}</td><td>{order.orderTypeName}</td><td>{formatMoney(order.total)}</td><td className={order.balance > 0 ? 'money-pending' : 'money-paid'}>{formatMoney(order.balance)}</td><td><StatusBadge status={order.status} /></td><td><div className="row-actions"><Link className="icon-button" to={`/orders/${order._id}`} title="Ver"><Eye size={17} /></Link>{can('orders:edit') && order.status !== 'Cancelado' && <Link className="icon-button" to={`/orders/${order._id}/edit`} title="Editar"><Edit3 size={17} /></Link>}{can('orders:download') && <button className="icon-button" title="Abrir PDF" onClick={() => void pdf(order)}><Download size={17} /></button>}</div></td></tr>)}</tbody></table>{!data.length && <EmptyState title="No encontramos órdenes" description="Ajusta la búsqueda o registra la primera orden." />}</div>}<Pagination page={pagination.page} pages={pagination.pages} onChange={(page) => void load(page)} /></section></>;
}
