import { useCallback, useEffect, useRef, useState, type FormEvent, type PointerEvent as ReactPointerEvent } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Banknote, ChevronLeft, Download, Edit3, FileText, History, Printer, ReceiptText, Smartphone, XCircle } from 'lucide-react';
import { PageHeader, StatusBadge } from '../components/Common';
import { Modal } from '../components/Modal';
import { useAuth } from '../contexts/AuthContext';
import { useToast } from '../contexts/ToastContext';
import { api, downloadFile, errorMessage, jsonBody, openPdf } from '../lib/api';
import { formatDate, formatMoney } from '../lib/format';
import { createUuid } from '../lib/uuid';
import type { ServiceOrder } from '../types';

const statuses = ['Pendiente', 'En diagnostico', 'En reparacion', 'Esperando refaccion', 'Listo para entregar', 'Entregado', 'Finalizado', 'Cancelado'];

export function OrderDetailsPage() {
  const { id } = useParams(); const { can } = useAuth(); const toast = useToast();
  const [order, setOrder] = useState<ServiceOrder | null>(null); const [loading, setLoading] = useState(true);
  const [paymentOpen, setPaymentOpen] = useState(false); const [statusOpen, setStatusOpen] = useState(false); const [saving, setSaving] = useState(false);
  const [payment, setPayment] = useState({ amount: 0, paymentMethod: 'Efectivo' as 'Efectivo' | 'Transferencia' | 'Tarjeta' | 'Mixto', cashAmount: 0, transferAmount: 0, cardAmount: 0, reference: '', notes: '' });
  const [statusForm, setStatusForm] = useState({ status: '', note: '' });
  const [signatureOpen, setSignatureOpen] = useState(false); const [receivedBy, setReceivedBy] = useState(''); const signatureRef = useRef<HTMLCanvasElement>(null); const drawing = useRef(false);
  const load = useCallback(async () => { if (!id) return; setLoading(true); try { const response = await api<{ data: ServiceOrder }>(`/service-orders/${id}`); setOrder(response.data); setPayment((value) => ({ ...value, amount: response.data.balance })); setStatusForm({ status: response.data.status, note: '' }); } catch (error) { toast.error(errorMessage(error)); } finally { setLoading(false); } }, [id, toast]);
  useEffect(() => { void load(); }, [load]);

  const addPayment = async (event: FormEvent) => { event.preventDefault(); if (!id) return; const parts = payment.paymentMethod === 'Efectivo' ? { cashAmount: payment.amount, transferAmount: 0, cardAmount: 0 } : payment.paymentMethod === 'Transferencia' ? { cashAmount: 0, transferAmount: payment.amount, cardAmount: 0 } : payment.paymentMethod === 'Tarjeta' ? { cashAmount: 0, transferAmount: 0, cardAmount: payment.amount } : { cashAmount: payment.cashAmount, transferAmount: payment.transferAmount, cardAmount: payment.cardAmount }; setSaving(true); try { const response = await api<{ data: ServiceOrder; message: string }>(`/service-orders/${id}/payments`, { method: 'POST', ...jsonBody({ ...payment, ...parts, amount: parts.cashAmount + parts.transferAmount + parts.cardAmount, idempotencyKey: createUuid() }) }); setOrder(response.data); setPaymentOpen(false); toast.success(response.message); } catch (error) { toast.error(errorMessage(error)); } finally { setSaving(false); } };
  const changeStatus = async (event: FormEvent) => { event.preventDefault(); if (!id) return; setSaving(true); try { const response = await api<{ data: ServiceOrder; message: string }>(`/service-orders/${id}/status`, { method: 'POST', ...jsonBody(statusForm) }); setOrder(response.data); setStatusOpen(false); toast.success(response.message); } catch (error) { toast.error(errorMessage(error)); } finally { setSaving(false); } };
  const cancelPayment = async (paymentId: string) => { if (!id) return; const reason = prompt('Motivo de cancelación del abono:'); if (!reason) return; try { const response = await api<{ data: ServiceOrder; message: string }>(`/service-orders/${id}/payments/${paymentId}/cancel`, { method: 'POST', ...jsonBody({ reason }) }); setOrder(response.data); toast.success(response.message); } catch (error) { toast.error(errorMessage(error)); } };
  const pdf = async (format: 'a4' | 'thermal58' | 'thermal80') => { if (!id) return; try { await openPdf(`/api/service-orders/${id}/pdf?format=${format}`); } catch (error) { toast.error(errorMessage(error)); } };
  const salesNote = async () => { if (!id || !order) return; try { await downloadFile(`/api/service-orders/${id}/sales-note`, `nota-venta-${order.folio}.pdf`); toast.success('Nota de venta descargada.'); } catch (error) { toast.error(errorMessage(error)); } };
  const draw = (event: ReactPointerEvent<HTMLCanvasElement>) => { const canvas = signatureRef.current; if (!canvas || !drawing.current) return; const rect = canvas.getBoundingClientRect(); const ctx = canvas.getContext('2d'); if (!ctx) return; ctx.lineWidth = 2.4; ctx.lineCap = 'round'; ctx.strokeStyle = '#0f172a'; const x = (event.clientX - rect.left) * canvas.width / rect.width; const y = (event.clientY - rect.top) * canvas.height / rect.height; ctx.lineTo(x, y); ctx.stroke(); ctx.beginPath(); ctx.moveTo(x, y); };
  const saveSignature = async () => { if (!id || !order || !signatureRef.current || receivedBy.trim().length < 2) return toast.error('Escribe el nombre de quien recibe.'); setSaving(true); try { const result = await api<{ data: ServiceOrder; message: string }>(`/service-orders/${id}/delivery-signature`, { method: 'POST', ...jsonBody({ dataUrl: signatureRef.current.toDataURL('image/png'), signedByName: 'Técnico responsable', receivedBy }) }); setOrder(result.data); setSignatureOpen(false); toast.success(result.message); } catch (error) { toast.error(errorMessage(error)); } finally { setSaving(false); } };

  if (loading) return <div className="loading-panel page-loading"><div className="spinner" />Cargando orden…</div>;
  if (!order) return <div className="empty-state"><strong>Orden no encontrada</strong><Link to="/orders">Regresar a órdenes</Link></div>;
  const appliedPayments = order.payments.filter((item) => item.status === 'Aplicado');
  const materialCost = order.materials.reduce((sum, item) => sum + item.quantity * item.unitCost, 0);
  return <>
    <PageHeader title={order.folio} description={`${order.orderTypeName} · registrada por ${order.createdByName}`} actions={<div className="page-actions"><Link className="button button-secondary" to="/orders"><ChevronLeft size={18} />Órdenes</Link>{can('orders:edit') && order.status !== 'Cancelado' && <Link className="button button-secondary" to={`/orders/${order._id}/edit`}><Edit3 size={18} />Editar</Link>}{can('orders:pay') && order.balance > 0 && order.status !== 'Cancelado' && <button className="button button-primary" onClick={() => setPaymentOpen(true)}><Banknote size={18} />Registrar abono</button>}</div>} />
    <div className="detail-grid">
      <div className="detail-main">
        <section className="panel"><div className="panel-header"><div><h2>Información de la orden</h2><p>{formatDate(order.orderDate, true)}</p></div><button className="status-button" disabled={!can('orders:status')} onClick={() => setStatusOpen(true)}><StatusBadge status={order.status} /></button></div>
          <div className="info-grid"><div><span>Cliente</span><strong>{order.clientSnapshot.name}</strong></div><div><span>Teléfono</span><strong>{order.clientSnapshot.phone}</strong></div><div><span>Correo</span><strong>{order.clientSnapshot.email || '—'}</strong></div><div><span>Dirección</span><strong>{order.clientSnapshot.address || '—'}</strong></div>{order.customerReference && <div className="info-span"><span>Referencia</span><strong>{order.customerReference}</strong></div>}</div>
        </section>
        <section className="panel"><div className="panel-header"><div><h2>Equipos recibidos</h2><p>{order.equipment.length} equipo(s) registrado(s).</p></div><Smartphone /></div><div className="equipment-details">{order.equipment.map((item, index) => <article key={item._id || index}><div className="equipment-number">{index + 1}</div><div><h3>{item.equipmentType} · {item.brand || 'Sin marca'} {item.model}</h3>{item.serialNumber && <p><strong>Serie/IMEI:</strong> {item.serialNumber}</p>}{item.accessories.length > 0 && <p><strong>Accesorios:</strong> {item.accessories.join(', ')}</p>}{item.observations && <p><strong>Observaciones:</strong> {item.observations}</p>}</div></article>)}</div></section>
        {order.photos.length > 0 && <section className="panel"><div className="panel-header"><div><h2>Evidencias</h2><p>{order.photos.length} de 5 fotografías.</p></div></div><div className="photo-grid">{order.photos.map((photo) => <a href={`/api/files/${photo.filename}`} target="_blank" rel="noreferrer" key={photo._id}><img loading="lazy" src={`/api/files/${photo.filename}`} alt={photo.originalName} /><span>{photo.originalName}</span></a>)}</div></section>}
        {order.materials.length > 0 && <section className="panel"><div className="panel-header"><div><h2>Refacciones y materiales</h2><p>Importe agregado al servicio: {formatMoney(materialCost)}</p></div></div><div className="table-wrap"><table><thead><tr><th>Descripción</th><th>Cantidad</th><th>Precio unitario</th><th>Importe</th><th>Proveedor</th></tr></thead><tbody>{order.materials.map((item, index) => <tr key={item._id || index}><td>{item.description}</td><td>{item.quantity}</td><td>{formatMoney(item.unitCost)}</td><td>{formatMoney(item.quantity * item.unitCost)}</td><td>{item.supplier || '—'}</td></tr>)}</tbody></table></div></section>}
        <section className="panel"><div className="panel-header"><div><h2>Historial de estados</h2><p>Trazabilidad de la orden.</p></div><History /></div><div className="timeline">{order.statusHistory.slice().reverse().map((item) => <div className="timeline-item" key={item._id}><span /><div><strong>{item.status}</strong><small>{formatDate(item.changedAt, true)} · {item.changedByName}</small>{item.note && <p>{item.note}</p>}</div></div>)}</div></section>
      </div>
      <aside className="detail-aside">
        <section className="panel payment-summary"><h2>Resumen financiero</h2><div><span>Servicio</span><strong>{formatMoney(order.serviceAmount ?? order.total - materialCost)}</strong></div><div><span>Refacciones</span><strong>{formatMoney(materialCost)}</strong></div><div><span>Total</span><strong>{formatMoney(order.total)}</strong></div><div><span>Abonado</span><strong className="money-paid">{formatMoney(order.paidAmount)}</strong></div><div className="balance-row"><span>Saldo pendiente</span><strong>{formatMoney(order.balance)}</strong></div>{order.balance <= 0 && <span className="paid-stamp">PAGADO</span>}</section>
        <section className="panel"><div className="panel-header"><div><h2>Abonos</h2><p>{appliedPayments.length} aplicado(s).</p></div></div><div className="payment-list">{order.payments.map((item) => <div className={`payment-item ${item.status === 'Cancelado' ? 'cancelled' : ''}`} key={item._id}><div><strong>{formatMoney(item.amount)}</strong><span>{item.paymentMethod} · {formatDate(item.paidAt, true)}</span>{item.paymentMethod === 'Mixto' && <small>Efectivo {formatMoney(item.cashAmount)} · Transferencia {formatMoney(item.transferAmount)} · Tarjeta {formatMoney(item.cardAmount)}</small>}{item.reference && <small>Ref. {item.reference}</small>}</div>{can('orders:cancel') && item.status === 'Aplicado' && <button className="icon-button danger" title="Cancelar abono" onClick={() => void cancelPayment(item._id)}><XCircle size={17} /></button>}</div>)}{!order.payments.length && <p className="muted">Sin abonos registrados.</p>}</div></section>
        {order.deliverySignature?.dataUrl && <section className="panel"><h2>Firma del técnico que entrega</h2><img className="signature-preview" src={order.deliverySignature.dataUrl} alt="Firma del técnico" /><small>Recibió: {order.deliverySignature.receivedBy} · {formatDate(order.deliverySignature.signedAt, true)}</small></section>}{can('orders:status') && order.balance <= 0 && order.status !== 'Cancelado' && !order.deliverySignature?.dataUrl && <button className="button button-primary button-block" onClick={() => setSignatureOpen(true)}>Firmar entrega del equipo</button>}
        {can('orders:download') && <section className="panel"><h2>Impresión y descarga</h2><div className="print-actions"><button className="button button-primary" onClick={() => void salesNote()}><ReceiptText size={18} />Descargar nota de venta</button><button className="button button-secondary" onClick={() => void pdf('a4')}><FileText size={18} />Reporte A4 con fotos</button><button className="button button-secondary" onClick={() => void pdf('thermal58')}><Printer size={18} />Ticket 58 mm</button><button className="button button-secondary" onClick={() => void pdf('thermal80')}><Download size={18} />Ticket 80 mm</button></div></section>}
      </aside>
    </div>
    <Modal open={paymentOpen} title="Registrar abono" onClose={() => setPaymentOpen(false)}><form onSubmit={addPayment}><div className="notice">Saldo actual: <strong>{formatMoney(order.balance)}</strong></div><div className="payment-method-buttons">{(['Efectivo', 'Transferencia', 'Tarjeta', 'Mixto'] as const).map((method) => <button type="button" className={`button ${payment.paymentMethod === method ? 'button-primary' : 'button-secondary'}`} onClick={() => setPayment({ ...payment, paymentMethod: method })} key={method}>{method}</button>)}</div>{payment.paymentMethod !== 'Mixto' && <label className="field"><span>Cantidad *</span><input autoFocus type="number" min="0.01" max={order.balance} step="0.01" value={payment.amount} onChange={(e) => setPayment({ ...payment, amount: Number(e.target.value) })} required /></label>}{payment.paymentMethod === 'Mixto' && <div className="form-grid three"><label className="field"><span>En efectivo</span><input type="number" min="0" step="0.01" value={payment.cashAmount} onChange={(e) => setPayment({ ...payment, cashAmount: Number(e.target.value) })} /></label><label className="field"><span>En transferencia</span><input type="number" min="0" step="0.01" value={payment.transferAmount} onChange={(e) => setPayment({ ...payment, transferAmount: Number(e.target.value) })} /></label><label className="field"><span>En tarjeta</span><input type="number" min="0" step="0.01" value={payment.cardAmount} onChange={(e) => setPayment({ ...payment, cardAmount: Number(e.target.value) })} /></label></div>}{(payment.paymentMethod === 'Transferencia' || payment.paymentMethod === 'Tarjeta' || payment.paymentMethod === 'Mixto') && <label className="field"><span>Referencia bancaria *</span><input value={payment.reference} onChange={(e) => setPayment({ ...payment, reference: e.target.value })} required minLength={3} /></label>}<label className="field"><span>Notas</span><textarea rows={2} value={payment.notes} onChange={(e) => setPayment({ ...payment, notes: e.target.value })} /></label><div className="modal-actions"><button type="button" className="button button-secondary" onClick={() => setPaymentOpen(false)}>Cancelar</button><button className="button button-primary" disabled={saving}>{saving ? 'Aplicando…' : 'Aplicar abono'}</button></div></form></Modal>
    <Modal open={statusOpen} title="Cambiar estado" onClose={() => setStatusOpen(false)}><form onSubmit={changeStatus}><label className="field"><span>Nuevo estado</span><select value={statusForm.status} onChange={(e) => setStatusForm({ ...statusForm, status: e.target.value })}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></label><label className="field"><span>Nota para la bitácora</span><textarea rows={3} value={statusForm.note} onChange={(e) => setStatusForm({ ...statusForm, note: e.target.value })} placeholder="Trabajo realizado, diagnóstico o motivo del cambio" /></label>{statusForm.status === 'Cancelado' && order.paidAmount > 0 && <div className="warning">Antes de cancelar la orden debes cancelar sus abonos aplicados.</div>}<div className="modal-actions"><button type="button" className="button button-secondary" onClick={() => setStatusOpen(false)}>Cerrar</button><button className="button button-primary" disabled={saving}>Actualizar estado y bitácora</button></div></form></Modal>
    <Modal open={signatureOpen} title="Firma del técnico que entrega" onClose={() => setSignatureOpen(false)}><label className="field"><span>Nombre de quien recibe *</span><input value={receivedBy} onChange={(e) => setReceivedBy(e.target.value)} /></label><p className="form-hint">El técnico responsable debe firmar la entrega del equipo.</p><canvas ref={signatureRef} width={700} height={220} className="signature-pad" onPointerDown={(e) => { drawing.current = true; e.currentTarget.setPointerCapture(e.pointerId); }} onPointerMove={draw} onPointerUp={() => { drawing.current = false; signatureRef.current?.getContext('2d')?.beginPath(); }} /><div className="modal-actions"><button type="button" className="button button-secondary" onClick={() => signatureRef.current?.getContext('2d')?.clearRect(0, 0, 700, 220)}>Limpiar</button><button type="button" className="button button-primary" disabled={saving} onClick={() => void saveSignature()}>Guardar firma y entregar</button></div></Modal>
  </>;
}
