import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Edit3, Plus } from 'lucide-react';
import { EmptyState, PageHeader, Pagination, SearchInput } from '../components/Common';
import { Modal } from '../components/Modal';
import { api, errorMessage, jsonBody, query } from '../lib/api';
import { useToast } from '../contexts/ToastContext';
import { useAuth } from '../contexts/AuthContext';
import type { Pagination as PaginationType } from '../types';
type Item = { _id: string; name: string; description: string; active: boolean };
export function QuotationTypesPage() {
  const toast = useToast(); const { can } = useAuth(); const [data, setData] = useState<Item[]>([]); const [pagination, setPagination] = useState<PaginationType>({ page: 1, limit: 10, total: 0, pages: 0 }); const [search, setSearch] = useState(''); const [modal, setModal] = useState(false); const [editing, setEditing] = useState<Item | null>(null); const [form, setForm] = useState({ name: '', description: '', active: true });
  const load = useCallback(async (page = 1) => { try { const r = await api<{ data: Item[]; pagination: PaginationType }>(`/quotation-types?${query({ page, limit: 10, search, active: 'all' })}`); setData(r.data); setPagination(r.pagination); } catch (e) { toast.error(errorMessage(e)); } }, [search, toast]);
  useEffect(() => { void load(); }, [load]);
  const open = (item?: Item) => { setEditing(item || null); setForm(item ? { name: item.name, description: item.description, active: item.active } : { name: '', description: '', active: true }); setModal(true); };
  const submit = async (e: FormEvent) => { e.preventDefault(); try { const r = await api<{ message: string }>(editing ? `/quotation-types/${editing._id}` : '/quotation-types', { method: editing ? 'PUT' : 'POST', ...jsonBody(form) }); toast.success(r.message); setModal(false); await load(pagination.page); } catch (error) { toast.error(errorMessage(error)); } };
  return <><PageHeader title="Tipos de cotizaciones" description="Catálogo para clasificar futuras cotizaciones." actions={can('quotationTypes:edit') && <button className="button button-primary" onClick={() => open()}><Plus size={18} />Nuevo tipo</button>} /><section className="panel"><div className="toolbar"><SearchInput value={search} onChange={setSearch} placeholder="Buscar tipo…" /><span className="result-count">{pagination.total} tipos</span></div><div className="table-wrap"><table><thead><tr><th>Tipo</th><th>Descripción</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{data.map(item => <tr key={item._id}><td><strong>{item.name}</strong></td><td>{item.description || '—'}</td><td>{item.active ? 'Activo' : 'Inactivo'}</td><td>{can('quotationTypes:edit') && <button className="icon-button" onClick={() => open(item)}><Edit3 size={17} /></button>}</td></tr>)}</tbody></table>{!data.length && <EmptyState />}</div><Pagination page={pagination.page} pages={pagination.pages} onChange={load} /></section><Modal open={modal} title={editing ? 'Editar tipo' : 'Nuevo tipo de cotización'} onClose={() => setModal(false)}><form onSubmit={submit}><label className="field"><span>Nombre *</span><input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} required /></label><label className="field"><span>Descripción</span><textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label><label className="check-row"><input type="checkbox" checked={form.active} onChange={e => setForm({ ...form, active: e.target.checked })} /> Activo</label><div className="modal-actions"><button className="button button-primary">Guardar</button></div></form></Modal></>;
}
