import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { Camera, FileText, Plus, Trash2 } from 'lucide-react';
import { EmptyState, PageHeader, Pagination, SearchInput, StatusBadge } from '../components/Common';
import { Modal } from '../components/Modal';
import { api, errorMessage, openPdf, query } from '../lib/api';
import { useAuth } from '../contexts/AuthContext';
import { useToast } from '../contexts/ToastContext';
import { formatDate, formatMoney, localDateInput } from '../lib/format';
import type { Client, Pagination as PaginationType } from '../types';

type TypeItem = { _id: string; name: string };
type Quotation = { _id: string; folio: string; quotationDate: string; clientSnapshot: { name: string; phone: string }; quotationTypeName: string; total: number; status: string };
const equipment = () => ({ equipmentType: '', brand: '', model: '', serialNumber: '', observations: '' });
const material = () => ({ description: '', quantity: 1, unitPrice: 0 });

export function QuotationsPage() {
  const { can } = useAuth(); const toast = useToast(); const [data, setData] = useState<Quotation[]>([]); const [pagination, setPagination] = useState<PaginationType>({ page: 1, limit: 10, total: 0, pages: 0 }); const [search, setSearch] = useState(''); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [clients, setClients] = useState<Client[]>([]); const [types, setTypes] = useState<TypeItem[]>([]); const [clientSearch, setClientSearch] = useState(''); const [files, setFiles] = useState<File[]>([]);
  const [form, setForm] = useState({ quotationDate: localDateInput(), clientId: '', quotationTypeId: '', references: '', equipment: [equipment()], materials: [material()], serviceAmount: 0, notes: '' });
  const load = useCallback(async (page = 1) => { try { const result = await api<{ data: Quotation[]; pagination: PaginationType }>(`/quotations?${query({ page, limit: 10, search })}`); setData(result.data); setPagination(result.pagination); } catch (error) { toast.error(errorMessage(error)); } }, [search, toast]);
  useEffect(() => { void load(); }, [load]);
  const start = async () => { try { const [clientResult, typeResult] = await Promise.all([api<{ data: Client[] }>('/clients?limit=100'), api<{ data: TypeItem[] }>('/quotation-types?limit=100')]); setClients(clientResult.data); setTypes(typeResult.data); setOpen(true); } catch (error) { toast.error(errorMessage(error)); } };
  const filteredClients = useMemo(() => { const needle = clientSearch.toLocaleLowerCase('es-MX'); return clients.filter((item) => `${item.clientCode} ${item.firstName} ${item.lastName} ${item.phone}`.toLocaleLowerCase('es-MX').includes(needle)); }, [clients, clientSearch]);
  const materialsTotal = form.materials.reduce((sum, item) => sum + Number(item.quantity) * Number(item.unitPrice), 0); const total = form.serviceAmount + materialsTotal;
  const submit = async (event: FormEvent) => { event.preventDefault(); const body = new FormData(); body.append('payload', JSON.stringify({ ...form, quotationDate: new Date(`${form.quotationDate}T12:00:00`).toISOString() })); files.forEach((file) => body.append('photos', file)); setSaving(true); try { const result = await api<{ message: string }>('/quotations', { method: 'POST', body }); toast.success(result.message); setOpen(false); setForm({ quotationDate: localDateInput(), clientId: '', quotationTypeId: '', references: '', equipment: [equipment()], materials: [material()], serviceAmount: 0, notes: '' }); setFiles([]); await load(1); } catch (error) { toast.error(errorMessage(error)); } finally { setSaving(false); } };
  const pdf = async (item: Quotation) => { try { await openPdf(`/api/quotations/${item._id}/pdf`); } catch (error) { toast.error(errorMessage(error)); } };
  return <><PageHeader title="Cotizaciones" description="Crea y consulta propuestas de servicio con equipos, refacciones y evidencias." actions={can('quotations:create') && <button className="button button-primary" onClick={() => void start()}><Plus size={18} />Nueva cotización</button>} /><section className="panel"><div className="toolbar"><SearchInput value={search} onChange={setSearch} placeholder="Folio, cliente o tipo…" /><span className="result-count">{pagination.total} cotizaciones</span></div><div className="table-wrap"><table><thead><tr><th>Folio</th><th>Fecha</th><th>Cliente</th><th>Tipo</th><th>Total</th><th>Estado</th><th>PDF</th></tr></thead><tbody>{data.map((item) => <tr key={item._id}><td><strong>{item.folio}</strong></td><td>{formatDate(item.quotationDate)}</td><td><strong>{item.clientSnapshot.name}</strong><small>{item.clientSnapshot.phone}</small></td><td>{item.quotationTypeName}</td><td>{formatMoney(item.total)}</td><td><StatusBadge status={item.status} /></td><td><button className="icon-button" title="Abrir cotización PDF" onClick={() => void pdf(item)}><FileText /></button></td></tr>)}</tbody></table>{!data.length && <EmptyState title="No hay cotizaciones" description="Crea la primera cotización del taller." />}</div><Pagination page={pagination.page} pages={pagination.pages} onChange={(page) => void load(page)} /></section>
    <Modal open={open} title="Nueva cotización" size="large" onClose={() => setOpen(false)}><form onSubmit={submit}><div className="form-grid two"><label className="field"><span>Fecha *</span><input type="date" value={form.quotationDate} onChange={(e) => setForm({ ...form, quotationDate: e.target.value })} required /></label><label className="field"><span>Tipo de cotización *</span><select value={form.quotationTypeId} onChange={(e) => setForm({ ...form, quotationTypeId: e.target.value })} required><option value="">Seleccionar…</option>{types.map((item) => <option value={item._id} key={item._id}>{item.name}</option>)}</select></label><label className="field"><span>Buscar cliente por nombre o código</span><input value={clientSearch} onChange={(e) => setClientSearch(e.target.value)} placeholder="CLI-00001 o nombre" /><select value={form.clientId} onChange={(e) => setForm({ ...form, clientId: e.target.value })} required><option value="">Seleccionar resultado…</option>{filteredClients.map((item) => <option value={item._id} key={item._id}>{item.clientCode} · {item.firstName} {item.lastName}</option>)}</select></label><label className="field"><span>Referencias</span><textarea value={form.references} onChange={(e) => setForm({ ...form, references: e.target.value })} /></label></div>
      <div className="form-section"><h3>Equipo mínimo obligatorio</h3>{form.equipment.map((item, index) => <div className="form-grid three" key={index}><label className="field"><span>Equipo *</span><input value={item.equipmentType} onChange={(e) => setForm({ ...form, equipment: form.equipment.map((x, i) => i === index ? { ...x, equipmentType: e.target.value } : x) })} required /></label><label className="field"><span>Marca</span><input value={item.brand} onChange={(e) => setForm({ ...form, equipment: form.equipment.map((x, i) => i === index ? { ...x, brand: e.target.value } : x) })} /></label><label className="field"><span>Modelo</span><input value={item.model} onChange={(e) => setForm({ ...form, equipment: form.equipment.map((x, i) => i === index ? { ...x, model: e.target.value } : x) })} /></label></div>)}</div>
      <div className="form-section"><div className="section-heading"><h3>Refacciones</h3><button type="button" className="button button-secondary" onClick={() => setForm({ ...form, materials: [...form.materials, material()] })}><Plus size={16} />Agregar</button></div>{form.materials.map((item, index) => <div className="material-row" key={index}><label className="field"><span>Descripción *</span><input value={item.description} onChange={(e) => setForm({ ...form, materials: form.materials.map((x, i) => i === index ? { ...x, description: e.target.value } : x) })} required /></label><label className="field"><span>Cantidad</span><input type="number" min="0.01" step="0.01" value={item.quantity} onChange={(e) => setForm({ ...form, materials: form.materials.map((x, i) => i === index ? { ...x, quantity: Number(e.target.value) } : x) })} /></label><label className="field"><span>Precio</span><input type="number" min="0" step="0.01" value={item.unitPrice} onChange={(e) => setForm({ ...form, materials: form.materials.map((x, i) => i === index ? { ...x, unitPrice: Number(e.target.value) } : x) })} /></label>{form.materials.length > 1 && <button type="button" className="icon-button danger material-delete" onClick={() => setForm({ ...form, materials: form.materials.filter((_, i) => i !== index) })}><Trash2 /></button>}</div>)}</div>
      <label className="upload-zone"><Camera /><strong>Agregar fotografías</strong><span>{files.length} de 5</span><input type="file" accept="image/jpeg,image/png" multiple onChange={(e) => setFiles(Array.from(e.target.files || []).slice(0, 5))} /></label><label className="field"><span>Notas</span><textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label><div className="service-total-final"><label className="field"><span>Total del servicio *</span><input type="number" min="0" step="0.01" value={form.serviceAmount} onChange={(e) => setForm({ ...form, serviceAmount: Number(e.target.value) })} required /></label><div className="order-total-preview"><span>Servicio: <strong>{formatMoney(form.serviceAmount)}</strong></span><span>Refacciones: <strong>{formatMoney(materialsTotal)}</strong></span><span>Total: <strong>{formatMoney(total)}</strong></span></div></div><div className="modal-actions"><button type="button" className="button button-secondary" onClick={() => setOpen(false)}>Cancelar</button><button className="button button-primary" disabled={saving}>{saving ? 'Guardando…' : 'Guardar cotización'}</button></div></form></Modal></>;
}
