import { useEffect, useState, type FormEvent } from 'react';
import { Building2, Image, Info, KeyRound, Palette, Save, ShieldCheck, Trash2 } from 'lucide-react';
import { PageHeader } from '../components/Common';
import { useAuth } from '../contexts/AuthContext';
import { useToast } from '../contexts/ToastContext';
import { api, errorMessage, jsonBody } from '../lib/api';
import type { Settings } from '../types';

type Section = 'business' | 'password' | 'control' | 'appearance' | 'system';
const defaults: Settings = { businessName: '', brandName: 'Soportepic Servicio', slogan: '', address: '', postalCode: '', phone: '', email: '', social: { facebook: '', instagram: '', whatsapp: '', website: '' }, logoUrl: '', printFormat: 'a4', ticketHeader: '', ticketFooter: '', timezone: 'America/Mazatlan', themeMode: 'system', primaryColor: '#2563eb', fontFamily: 'system', fontScale: 1, showThemeToggle: true, showUserName: true, showDateTime: true, systemVersion: '1.3.0', rightsText: 'Derechos reservados Soportepic', supportPhone: '311-135-45-85' };
const sections: { id: Section; label: string; icon: typeof Building2 }[] = [{ id: 'business', label: 'Datos del negocio', icon: Building2 }, { id: 'password', label: 'Cambiar contraseña', icon: KeyRound }, { id: 'control', label: 'Panel de control', icon: ShieldCheck }, { id: 'appearance', label: 'Impresión y apariencia', icon: Palette }, { id: 'system', label: 'Información del sistema', icon: Info }];

export function SettingsPage() {
  const { can, refresh, user } = useAuth(); const toast = useToast(); const [section, setSection] = useState<Section>('business'); const [form, setForm] = useState<Settings>(defaults); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [logo, setLogo] = useState<File | null>(null); const [passwords, setPasswords] = useState({ currentPassword: '', newPassword: '', confirm: '' }); const [resetText, setResetText] = useState('');
  useEffect(() => { api<{ data: Settings }>('/settings').then((r) => setForm({ ...defaults, ...r.data })).catch((e) => toast.error(errorMessage(e))).finally(() => setLoading(false)); }, [toast]);
  const save = async (event?: FormEvent) => { event?.preventDefault(); setSaving(true); try { const { systemVersion: _v, rightsText: _r, supportPhone: _s, logoFilename: _l, ...payload } = form; const result = await api<{ data: Settings; message: string }>('/settings', { method: 'PUT', ...jsonBody(payload) }); setForm({ ...defaults, ...result.data }); toast.success(result.message); } catch (e) { toast.error(errorMessage(e)); } finally { setSaving(false); } };
  const uploadLogo = async () => { if (!logo) return; const body = new FormData(); body.append('logo', logo); setSaving(true); try { const r = await api<{ data: Settings; message: string }>('/settings/logo', { method: 'POST', body }); setForm({ ...defaults, ...r.data }); setLogo(null); toast.success(r.message); } catch (e) { toast.error(errorMessage(e)); } finally { setSaving(false); } };
  const changePassword = async (event: FormEvent) => { event.preventDefault(); if (passwords.newPassword !== passwords.confirm) return toast.error('Las contraseñas nuevas no coinciden.'); setSaving(true); try { const r = await api<{ message: string }>('/auth/change-password', { method: 'POST', ...jsonBody({ currentPassword: passwords.currentPassword, newPassword: passwords.newPassword }) }); toast.success(r.message); setPasswords({ currentPassword: '', newPassword: '', confirm: '' }); await refresh(); } catch (e) { toast.error(errorMessage(e)); } finally { setSaving(false); } };
  const resetDatabase = async () => { if (resetText !== 'REINICIAR DATOS') return toast.error('Escribe exactamente REINICIAR DATOS.'); setSaving(true); try { const r = await api<{ message: string }>('/settings/reset-data', { method: 'POST', ...jsonBody({ confirmation: resetText }) }); toast.success(r.message); setResetText(''); window.setTimeout(() => window.location.reload(), 1200); } catch (e) { toast.error(errorMessage(e)); } finally { setSaving(false); } };
  if (loading) return <div className="loading-panel page-loading"><div className="spinner" />Cargando configuración…</div>;
  return <><PageHeader title="Configuración" description="Administra el sistema mediante secciones organizadas." /><div className="settings-tabs">{sections.map(({ id, label, icon: Icon }) => <button key={id} className={section === id ? 'active' : ''} onClick={() => setSection(id)}><Icon size={19} /><span>{label}</span></button>)}</div>
    {section === 'business' && <form className="panel settings-section" onSubmit={save}><h2>Datos del negocio</h2><p className="muted">Información utilizada en reportes, tickets y notas.</p><fieldset disabled={!can('settings:edit')}><div className="form-grid two"><label className="field"><span>Nombre comercial *</span><input value={form.businessName} onChange={(e) => setForm({ ...form, businessName: e.target.value })} required /></label><label className="field"><span>Marca del sistema *</span><input value={form.brandName} onChange={(e) => setForm({ ...form, brandName: e.target.value })} required /></label><label className="field field-span-2"><span>Eslogan</span><input value={form.slogan} onChange={(e) => setForm({ ...form, slogan: e.target.value })} /></label><label className="field"><span>Dirección</span><input value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} /></label><label className="field"><span>Código postal</span><input value={form.postalCode} onChange={(e) => setForm({ ...form, postalCode: e.target.value })} /></label><label className="field"><span>Teléfono</span><input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></label><label className="field"><span>Correo</span><input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label></div><div className="logo-config">{form.logoUrl ? <img src={`${form.logoUrl}?v=${form.logoFilename || 'actual'}`} alt="Logotipo" /> : <div className="logo-placeholder"><Image />Sin logotipo</div>}<label className="button button-secondary">Elegir logotipo<input hidden type="file" accept="image/jpeg,image/png" onChange={(e) => setLogo(e.target.files?.[0] || null)} /></label><button type="button" className="button button-primary" disabled={!logo || saving} onClick={() => void uploadLogo()}>Cargar</button></div></fieldset>{can('settings:edit') && <div className="form-submit"><button className="button button-primary" disabled={saving}><Save size={18} />Guardar datos</button></div>}</form>}
    {section === 'password' && <form className="panel settings-section narrow" onSubmit={changePassword}><h2>Cambiar contraseña</h2><label className="field"><span>Contraseña actual</span><input type="password" value={passwords.currentPassword} onChange={(e) => setPasswords({ ...passwords, currentPassword: e.target.value })} required /></label><label className="field"><span>Nueva contraseña</span><input type="password" minLength={8} value={passwords.newPassword} onChange={(e) => setPasswords({ ...passwords, newPassword: e.target.value })} required /></label><label className="field"><span>Confirmar contraseña</span><input type="password" value={passwords.confirm} onChange={(e) => setPasswords({ ...passwords, confirm: e.target.value })} required /></label><button className="button button-primary" disabled={saving}>Actualizar contraseña</button></form>}
    {section === 'appearance' && <form className="panel settings-section" onSubmit={save}><h2>Impresión y apariencia</h2><div className="form-grid two"><label className="field"><span>Formato de impresión</span><select value={form.printFormat} onChange={(e) => setForm({ ...form, printFormat: e.target.value as Settings['printFormat'] })}><option value="a4">Hoja A4</option><option value="thermal58">Térmica 58 mm</option><option value="thermal80">Térmica 80 mm</option></select></label><label className="field"><span>Modo visual</span><select value={form.themeMode} onChange={(e) => setForm({ ...form, themeMode: e.target.value as Settings['themeMode'] })}><option value="system">Según dispositivo</option><option value="light">Claro</option><option value="dark">Oscuro</option></select></label><label className="field"><span>Color principal</span><input type="color" value={form.primaryColor} onChange={(e) => setForm({ ...form, primaryColor: e.target.value })} /></label><label className="field"><span>Tipo de letra</span><select value={form.fontFamily} onChange={(e) => setForm({ ...form, fontFamily: e.target.value as Settings['fontFamily'] })}><option value="system">Predeterminada</option><option value="inter">Inter</option><option value="arial">Arial</option><option value="georgia">Georgia</option></select></label><label className="field"><span>Tamaño: {Math.round(form.fontScale * 100)}%</span><input type="range" min="0.85" max="1.25" step="0.05" value={form.fontScale} onChange={(e) => setForm({ ...form, fontScale: Number(e.target.value) })} /></label><label className="field"><span>Zona horaria</span><select value={form.timezone} onChange={(e) => setForm({ ...form, timezone: e.target.value })}><option value="America/Mazatlan">Tepic / Mazatlán</option><option value="America/Mexico_City">Ciudad de México</option><option value="America/Tijuana">Tijuana</option></select></label></div><div className="visibility-options"><label><input type="checkbox" checked={form.showThemeToggle} onChange={(e) => setForm({ ...form, showThemeToggle: e.target.checked })} /> Mostrar botón claro/oscuro en la app</label><label><input type="checkbox" checked={form.showUserName} onChange={(e) => setForm({ ...form, showUserName: e.target.checked })} /> Mostrar nombre y rol</label><label><input type="checkbox" checked={form.showDateTime} onChange={(e) => setForm({ ...form, showDateTime: e.target.checked })} /> Mostrar fecha y hora</label></div><label className="field"><span>Encabezado del ticket</span><textarea value={form.ticketHeader} onChange={(e) => setForm({ ...form, ticketHeader: e.target.value })} /></label><label className="field"><span>Pie del ticket</span><textarea value={form.ticketFooter} onChange={(e) => setForm({ ...form, ticketFooter: e.target.value })} /></label><div className="form-submit"><button className="button button-primary" disabled={saving}><Save size={18} />Guardar apariencia</button></div></form>}
    {section === 'control' && <section className="panel settings-section"><h2>Panel de control</h2><div className="system-card"><div><span>Usuario</span><strong>{user?.name}</strong></div><div><span>Rol</span><strong>{user?.role === 'admin' ? 'Administrador' : 'Operador'}</strong></div></div>{user?.role === 'admin' && <div className="danger-zone"><h3><Trash2 size={19} /> Reiniciar datos del sistema</h3><p>Elimina clientes, órdenes, cotizaciones, garantías, gastos, fotografías, configuración y contadores. Los usuarios se conservan.</p><label className="field"><span>Escribe REINICIAR DATOS para confirmar</span><input value={resetText} onChange={(e) => setResetText(e.target.value)} /></label><button className="button button-danger" disabled={saving || resetText !== 'REINICIAR DATOS'} onClick={() => void resetDatabase()}><Trash2 size={17} />Dejar base de datos en blanco</button></div>}</section>}
    {section === 'system' && <section className="panel settings-section narrow"><h2>Información del sistema</h2><div className="system-card"><div><span>Versión</span><strong>{form.systemVersion}</strong></div><div><span>Derechos</span><strong>{form.rightsText}</strong></div><div><span>Soporte técnico</span><strong>{form.supportPhone}</strong></div></div></section>}
  </>;
}
