import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Edit3, Plus, Shield, UserX } from 'lucide-react';
import { EmptyState, LoadingTable, PageHeader, Pagination, SearchInput } from '../components/Common';
import { Modal } from '../components/Modal';
import { useAuth } from '../contexts/AuthContext';
import { useToast } from '../contexts/ToastContext';
import { api, errorMessage, jsonBody, query } from '../lib/api';
import type { Pagination as PaginationType, User } from '../types';

const permissionLabels: Record<string, string> = {
  view: 'Consultar', create: 'Agregar', edit: 'Editar', deactivate: 'Desactivar', status: 'Cambiar estado', pay: 'Registrar abonos', print: 'Imprimir', download: 'Descargar', cancel: 'Cancelar'
};
const moduleLabels: Record<string, string> = { dashboard: 'Inicio', clients: 'Clientes', users: 'Usuarios', orderTypes: 'Tipos de orden', quotationTypes: 'Tipos de cotización', quotations: 'Cotizaciones', orders: 'Órdenes', warranties: 'Garantías', expenses: 'Gastos', reports: 'Reportes', settings: 'Configuración', controlPanel: 'Panel de control', audit: 'Auditoría' };
const emptyForm = { name: '', username: '', password: '', role: 'operator' as 'admin' | 'operator', permissions: [] as string[], active: true };

export function UsersPage() {
  const { can, user: current } = useAuth(); const toast = useToast();
  const [data, setData] = useState<User[]>([]); const [allPermissions, setAllPermissions] = useState<string[]>([]); const [pagination, setPagination] = useState<PaginationType>({ page: 1, limit: 10, total: 0, pages: 0 });
  const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [modal, setModal] = useState(false); const [editing, setEditing] = useState<User | null>(null); const [form, setForm] = useState(emptyForm); const [saving, setSaving] = useState(false);
  const load = useCallback(async (page = 1) => { setLoading(true); try { const [result, permissionResult] = await Promise.all([api<{ data: User[]; pagination: PaginationType }>(`/users?${query({ page, limit: 10, search })}`), api<{ permissions: string[] }>('/users/permissions')]); setData(result.data); setPagination(result.pagination); setAllPermissions(permissionResult.permissions); } catch (error) { toast.error(errorMessage(error)); } finally { setLoading(false); } }, [search, toast]);
  useEffect(() => { const id = setTimeout(() => void load(1), 250); return () => clearTimeout(id); }, [load]);
  const open = (item?: User) => { setEditing(item || null); setForm(item ? { name: item.name, username: item.username, password: '', role: item.role, permissions: [...item.permissions], active: item.active } : { ...emptyForm, permissions: allPermissions.filter((permission) => ['dashboard:view', 'clients:view', 'clients:create', 'clients:edit', 'orderTypes:view', 'orders:view', 'orders:create', 'orders:edit', 'orders:status', 'orders:pay', 'orders:print', 'orders:download', 'expenses:view', 'expenses:create', 'settings:view'].includes(permission)) }); setModal(true); };
  const toggle = (permission: string) => setForm((currentForm) => ({ ...currentForm, permissions: currentForm.permissions.includes(permission) ? currentForm.permissions.filter((item) => item !== permission) : [...currentForm.permissions, permission] }));
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { const payload = { ...form, permissions: form.role === 'admin' ? allPermissions : form.permissions, ...(editing ? { revision: editing.revision } : {}) }; if (editing && !payload.password) delete (payload as Partial<typeof payload>).password; const result = editing ? await api<{ message: string }>(`/users/${editing._id}`, { method: 'PUT', ...jsonBody(payload) }) : await api<{ message: string }>('/users', { method: 'POST', ...jsonBody(payload) }); toast.success(result.message); setModal(false); await load(pagination.page); } catch (error) { toast.error(errorMessage(error)); } finally { setSaving(false); } };
  const deactivate = async (item: User) => { if (!confirm(`¿Desactivar al usuario ${item.username}?`)) return; try { const result = await api<{ message: string }>(`/users/${item._id}/deactivate`, { method: 'PATCH' }); toast.success(result.message); await load(pagination.page); } catch (error) { toast.error(errorMessage(error)); } };
  const groups = Object.entries(allPermissions.reduce<Record<string, string[]>>((acc, permission) => { const [module] = permission.split(':'); if (module) (acc[module] ||= []).push(permission); return acc; }, {}));
  return <><PageHeader title="Usuarios y permisos" description="Controla exactamente lo que puede hacer cada persona." actions={can('users:create') && <button className="button button-primary" onClick={() => open()}><Plus size={18} />Nuevo usuario</button>} />
    <section className="panel"><div className="toolbar"><SearchInput value={search} onChange={setSearch} placeholder="Nombre, usuario o rol…" /><span className="result-count">{pagination.total} usuarios</span></div>{loading ? <LoadingTable /> : <div className="table-wrap"><table><thead><tr><th>Usuario</th><th>Nombre</th><th>Rol</th><th>Permisos</th><th>Último acceso</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{data.map((item) => <tr key={item._id}><td><strong>@{item.username}</strong>{item._id === current?._id && <small>Tu cuenta</small>}</td><td>{item.name}</td><td><span className={`role-chip role-${item.role}`}><Shield size={14} />{item.role === 'admin' ? 'Administrador' : 'Operador'}</span></td><td>{item.role === 'admin' ? 'Acceso completo' : `${item.permissions.length} permisos`}</td><td>{item.lastLoginAt ? new Date(item.lastLoginAt).toLocaleString('es-MX') : 'Nunca'}</td><td><span className={`status ${item.active ? 'status-activo' : 'status-cancelado'}`}>{item.active ? 'Activo' : 'Inactivo'}</span></td><td><div className="row-actions">{can('users:edit') && <button className="icon-button" onClick={() => open(item)}><Edit3 size={17} /></button>}{can('users:deactivate') && item.active && item._id !== current?._id && <button className="icon-button danger" onClick={() => void deactivate(item)}><UserX size={17} /></button>}</div></td></tr>)}</tbody></table>{!data.length && <EmptyState />}</div>}<Pagination page={pagination.page} pages={pagination.pages} onChange={(page) => void load(page)} /></section>
    <Modal open={modal} title={editing ? 'Editar usuario' : 'Nuevo usuario'} onClose={() => setModal(false)} size="large"><form onSubmit={submit}><div className="form-grid two"><label className="field"><span>Nombre completo *</span><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required minLength={2} /></label><label className="field"><span>Usuario *</span><input value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} required minLength={3} pattern="[a-zA-Z0-9._-]+" /></label><label className="field"><span>{editing ? 'Nueva contraseña (opcional)' : 'Contraseña *'}</span><input type="password" autoComplete="new-password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} required={!editing} minLength={editing && !form.password ? undefined : 8} /><small>8+ caracteres, mayúscula, minúscula y número.</small></label><label className="field"><span>Rol *</span><select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value as 'admin' | 'operator' })}><option value="operator">Operador</option><option value="admin">Administrador</option></select></label></div>
      <div className="permissions-heading"><div><h3>Permisos por función</h3><p>La API también verifica estos permisos; no solo se ocultan los botones.</p></div>{form.role === 'admin' && <span className="role-chip role-admin">Acceso completo</span>}</div>
      <div className={`permission-groups ${form.role === 'admin' ? 'disabled' : ''}`}>{groups.map(([module, permissions]) => <fieldset key={module} disabled={form.role === 'admin'}><legend>{moduleLabels[module] || module}</legend>{permissions.map((permission) => { const action = permission.split(':')[1] || permission; return <label className="check-row" key={permission}><input type="checkbox" checked={form.role === 'admin' || form.permissions.includes(permission)} onChange={() => toggle(permission)} /><span>{permissionLabels[action] || action}</span></label>; })}</fieldset>)}</div>
      <div className="modal-actions"><button type="button" className="button button-secondary" onClick={() => setModal(false)}>Cancelar</button><button className="button button-primary" disabled={saving}>{saving ? 'Guardando…' : 'Guardar usuario'}</button></div></form></Modal>
  </>;
}
