import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { FileText, Plus, ShieldCheck } from 'lucide-react';
import { EmptyState, PageHeader, Pagination, SearchInput, StatusBadge } from '../components/Common';
import { Modal } from '../components/Modal';
import { api, errorMessage, jsonBody, openPdf, query } from '../lib/api';
import { useToast } from '../contexts/ToastContext'; import { useAuth } from '../contexts/AuthContext'; import { formatDate } from '../lib/format'; import type { Pagination as PaginationType, ServiceOrder } from '../types';
type Warranty = { _id: string; warrantyCode: string; orderFolio: string; clientName: string; startDate: string; expirationDate: string; coveredParts: string[]; exclusionReason: string; status: string; claims: { _id: string; claimDate: string; description: string; resolution: string; status: string }[] };
export function WarrantiesPage() {
  const toast = useToast(); const { can } = useAuth(); const [data, setData] = useState<Warranty[]>([]); const [orders, setOrders] = useState<ServiceOrder[]>([]); const [pagination, setPagination] = useState<PaginationType>({ page: 1, limit: 10, total: 0, pages: 0 }); const [search, setSearch] = useState(''); const [modal, setModal] = useState(false); const [claimFor, setClaimFor] = useState<Warranty | null>(null); const [form, setForm] = useState({ serviceOrderId: '', startDate: new Date().toISOString().slice(0, 10), expirationDate: '', coveredParts: '', exclusionReason: '', terms: '' }); const [claim, setClaim] = useState({ description: '', resolution: '', status: 'Abierta' });
  const load = useCallback(async (page = 1) => { try { const [w, o] = await Promise.all([api<{ data: Warranty[]; pagination: PaginationType }>(`/warranties?${query({ page, limit: 10, search })}`), api<{ data: ServiceOrder[] }>('/service-orders?limit=100')]); setData(w.data); setPagination(w.pagination); setOrders(o.data); } catch (e) { toast.error(errorMessage(e)); } }, [search, toast]); useEffect(() => { void load(); }, [load]);
  const submit = async (e: FormEvent) => { e.preventDefault(); try { const r = await api<{ message: string }>('/warranties', { method: 'POST', ...jsonBody({ ...form, coveredParts: form.coveredParts.split(',').map(v => v.trim()).filter(Boolean) }) }); toast.success(r.message); setModal(false); await load(); } catch (er) { toast.error(errorMessage(er)); } };
  const addClaim = async (e: FormEvent) => { e.preventDefault(); if (!claimFor) return; try { const r = await api<{ message: string }>(`/warranties/${claimFor._id}/claims`, { method: 'POST', ...jsonBody(claim) }); toast.success(r.message); setClaimFor(null); await load(pagination.page); } catch (er) { toast.error(errorMessage(er)); } };
  const pdf = async (item: Warranty) => { try { await openPdf(`/api/warranties/${item._id}/pdf`); } catch (e) { toast.error(errorMessage(e)); } };
  return <><PageHeader title="Garantías" description="Cobertura, vencimientos e historial de reclamaciones." actions={can('warranties:edit') && <button className="button button-primary" onClick={() => setModal(true)}><Plus size={18} />Nueva garantía</button>} /><section className="panel"><div className="toolbar"><SearchInput value={search} onChange={setSearch} placeholder="Garantía, orden o cliente…" /><span className="result-count">{pagination.total} garantías</span></div><div className="table-wrap"><table><thead><tr><th>Garantía</th><th>Orden / cliente</th><th>Vigencia</th><th>Piezas cubiertas</th><th>Reclamaciones</th><th>Estado</th><th>PDF</th></tr></thead><tbody>{data.map(w => <tr key={w._id}><td><strong>{w.warrantyCode}</strong></td><td>{w.orderFolio}<small>{w.clientName}</small></td><td>{formatDate(w.startDate)}<small>al {formatDate(w.expirationDate)}</small></td><td>{w.coveredParts.join(', ')}</td><td><button className="button button-secondary" onClick={() => setClaimFor(w)}>{w.claims.length} · Agregar</button></td><td><StatusBadge status={w.status} /></td><td><button className="icon-button" title="Abrir garantía PDF" onClick={() => void pdf(w)}><FileText /></button></td></tr>)}</tbody></table>{!data.length && <EmptyState title="Sin garantías" description="Registra la garantía de una reparación entregada." />}</div><Pagination page={pagination.page} pages={pagination.pages} onChange={load} /></section>
  <Modal open={modal} title="Registrar garantía" onClose={() => setModal(false)} size="large"><form onSubmit={submit}><label className="field"><span>Orden *</span><select value={form.serviceOrderId} onChange={e => setForm({ ...form, serviceOrderId: e.target.value })} required><option value="">Selecciona…</option>{orders.map(o => <option value={o._id} key={o._id}>{o.folio} · {o.clientSnapshot.name}</option>)}</select></label><div className="form-grid two"><label className="field"><span>Inicio *</span><input type="date" value={form.startDate} onChange={e => setForm({ ...form, startDate: e.target.value })} required /></label><label className="field"><span>Vencimiento *</span><input type="date" value={form.expirationDate} onChange={e => setForm({ ...form, expirationDate: e.target.value })} required /></label></div><label className="field"><span>Piezas cubiertas *</span><input value={form.coveredParts} onChange={e => setForm({ ...form, coveredParts: e.target.value })} required /></label><label className="field"><span>Exclusiones</span><textarea value={form.exclusionReason} onChange={e => setForm({ ...form, exclusionReason: e.target.value })} /></label><label className="field"><span>Términos</span><textarea value={form.terms} onChange={e => setForm({ ...form, terms: e.target.value })} /></label><div className="modal-actions"><button className="button button-primary"><ShieldCheck size={18} />Guardar</button></div></form></Modal>
  <Modal open={Boolean(claimFor)} title="Agregar reclamación" onClose={() => setClaimFor(null)}><form onSubmit={addClaim}><label className="field"><span>Descripción *</span><textarea value={claim.description} onChange={e => setClaim({ ...claim, description: e.target.value })} required /></label><label className="field"><span>Estado</span><select value={claim.status} onChange={e => setClaim({ ...claim, status: e.target.value })}><option>Abierta</option><option>En revision</option><option>Resuelta</option><option>Rechazada</option></select></label><label className="field"><span>Resolución</span><textarea value={claim.resolution} onChange={e => setClaim({ ...claim, resolution: e.target.value })} /></label><div className="modal-actions"><button className="button button-primary">Guardar reclamación</button></div></form></Modal></>;
}
